#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II

bspc config border_width         3
bspc config window_gap          13
bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

