#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width            3
bspc config window_gap              8
bspc config split_ratio             0.618
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

setxkbmap -layout us,ro -option grp:alt_shift_toggle &

# Start GNOME settings daemons to restore GNOME-like config
/usr/libexec/gsd-xsettings &
/usr/libexec/gsd-keyboard &
/usr/libexec/gsd-power &
/usr/libexec/gsd-color &
/usr/libexec/gsd-housekeeping &
/usr/libexec/gsd-media-keys &

ptyxis &
